export const NOTIFICATIONS = {
  PROFILE_UPDATE: "profile_update",
  IMAGE_UPDATE: "image_update",
  APPROVAL_REQUEST: "approval_request",
  UPDATE_APPROVED: "update_approved",
  UPDATE_REJECTED: "update_rejected",
  PROFILE_CREATED: "profile_created",
  PASSWORD_UPDATED: "password_updated",
  AUCTION_CREATED: "auction_created",
  AUCTION_UPDATED: "auction_updated",
  TEAM_CREATED: "team_created",
  FEEDBACK: "feedback",
  GENERAL: "general",
} as const;

export type NotificationType = keyof typeof NOTIFICATIONS;

export const PENDING_UPDATES_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

export type PendingUpdateStatusType = keyof typeof PENDING_UPDATES_STATUS;

export const AUDIT_CHANGED_TYPE = {
  CREATE: "create",
  UPDATE: "update",
  DELETE: "delete",
};

export type AuditChangedType = keyof typeof AUDIT_CHANGED_TYPE;

export const NotificationMessage = {
  ACCOUNT_CREATE_BY_SELF: "ACCOUNT_CREATE_BY_SELF",
  ACCOUNT_CREATE_BY_ELSE: "ACCOUNT_CREATE_BY_ELSE",
  PASSWORD_UPDATED: "PASSWORD_UPDATED",
  ACCOUNT_UPDATE_BY_SELF: "ACCOUNT_UPDATE_BY_SELF",
  ACCOUNT_UPDATE_BY_ELSE: "ACCOUNT_UPDATE_BY_ELSE",
  IMAGE_UPDATE_BY_SELF: "IMAGE_UPDATE_BY_SELF",
  IMAGE_UPDATE_BY_ELSE: "IMAGE_UPDATE_BY_ELSE",
  STATUS_CHANGE_TO_NON_PLAYER: "STATUS_CHANGE_TO_NON_PLAYER",
  STATUS_CHANGE_TO_PLAYER: "STATUS_CHANGE_TO_PLAYER",
  CHANGE_ROLE_TO_ADMIN: "CHANGE_ROLE_TO_ADMIN",
  REMOVE_ROLE_FROM_ADMIN: "REMOVE_ROLE_FROM_ADMIN",
  APPROVED_PROFILE: "APPROVED_PROFILE",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  REQUEST_APPROVED: "REQUEST_APPROVED",
  APPROVAL_REQUEST: "APPROVAL_REQUEST",
  AUCTION_CREATE_BY_SELF: "AUCTION_CREATE_BY_SELF",
  AUCTION_UPDATE_BY_SELF: "AUCTION_UPDATE_BY_SELF",
  AUCTION_UPDATE_BY_ELSE: "AUCTION_UPDATE_BY_ELSE",
};

export const NOTIFICATION_ROLE = {
  SUPER_ADMIN: "Admin",
  ADMIN: "Admin",
  ORGANISER: "Organiser",
  OWNER: "Owner",
  PLAYER: "Self",
};
