CREATE TABLE banner (
  bannerId INT AUTO_INCREMENT PRIMARY KEY,
  heading VARCHAR(255),
  description VARCHAR(500),
  image VARCHAR(200),
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN DEFAULT true,
) AUTO_INCREMENT=1;


create TABLE discount (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description varchar (500),
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN DEFAULT true
)

create TABLE youtubevideos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  videoId VARCHAR(50),
  thumbnail VARCHAR(200),
  channelTitle VARCHAR(100),
  publishTime VARCHAR(30),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)