INSERT IGNORE INTO players (
    name, 
    mobile, 
    email, 
    isSubmitted, 
    isApproved, 
    state, 
    district, 
    isVerified, 
    isActive, 
    isNonPlayer
)
SELECT
    CONCAT(
        SUBSTRING('ABCDEFGHIJKLMNOPQRSTUVWXYZ', FLOOR(1 + RAND() * 26), 1),
        SUBSTRING(MD5(RAND()), 1, FLOOR(8 + RAND() * 8))
    ) AS name,
    CONCAT('8', LPAD(100000000 + n, 9, '0')) AS mobile,
    IF(RAND() < 0.7, CONCAT('user', n, '@example.com'), NULL) AS email,
    RAND() > 0.5 AS isSubmitted,
    RAND() > 0.5 AS isApproved,
    sd.state,
    sd.district,
    CASE
        WHEN RAND() < 0.2 THEN NULL
        WHEN RAND() < 0.5 THEN TRUE
        ELSE FALSE
    END AS isVerified,
    RAND() > 0.2 AS isActive,
    RAND() > 0.9 AS isNonPlayer
FROM (
    SELECT 
        a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 AS n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
    WHERE 
        a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 < 100000
) AS numbers
JOIN (
    SELECT 
        state,
        district,
        RAND() AS rand_order
    FROM state_districts
) sd
ORDER BY sd.rand_order
LIMIT 100000;


-- Temp State
CREATE TEMPORARY TABLE state_districts (
  state VARCHAR(30),
  district VARCHAR(50),
  INDEX (state)
);

-- Insert State and District Query
INSERT INTO state_districts (state, district) VALUES
-- Haryana
('Haryana', 'Mahendragarh'),
('Haryana', 'Panchkula'),
('Haryana', 'Panipat'),
('Haryana', 'Rewari'),
('Haryana', 'Rohtak'),
('Haryana', 'Sirsa'),
('Haryana', 'Sonipat'),
('Haryana', 'Yamunanagar'),
('Haryana', 'Ambala'),
('Haryana', 'Bhiwani'),
('Haryana', 'Charki Dadri'),
('Haryana', 'Faridabad'),
('Haryana', 'Fatehabad'),
('Haryana', 'Gurugram'),
('Haryana', 'Hisar'),
('Haryana', 'Jhajjar'),
('Haryana', 'Jind'),
('Haryana', 'Karnal'),
('Haryana', 'Kurukshetra'),
('Haryana', 'Nuh'),
('Haryana', 'Palwal'),
('Haryana', 'Kaithal'),

-- Delhi
('Delhi', 'North East'),
('Delhi', 'North'),
('Delhi', 'North West'),
('Delhi', 'Shahdara'),
('Delhi', 'South East'),
('Delhi', 'South West'),
('Delhi', 'West'),
('Delhi', 'Central'),
('Delhi', 'East'),
('Delhi', 'New Delhi'),
('Delhi', 'South');



INSERT INTO state_districts (state, district) VALUES
-- Karnataka
('Karnataka', 'Bengaluru Urban'),
('Karnataka', 'Hassan'),
('Karnataka', 'Mysuru'),
('Karnataka', 'Bagalkote'),
('Karnataka', 'Ballari'),
('Karnataka', 'Belagavi'),
('Karnataka', 'Bengaluru Rural'),
('Karnataka', 'Bidar'),
('Karnataka', 'Chamarajanagara'),
('Karnataka', 'Chikkaballapura'),
('Karnataka', 'Chikkamagaluru'),
('Karnataka', 'Chitradurga'),
('Karnataka', 'Dakshina Kannada'),
('Karnataka', 'Davanagere'),
('Karnataka', 'Dharwad'),
('Karnataka', 'Gadag'),
('Karnataka', 'Haveri'),
('Karnataka', 'Kalaburagi'),
('Karnataka', 'Kodagu'),
('Karnataka', 'Kolar'),
('Karnataka', 'Koppal'),
('Karnataka', 'Mandya'),
('Karnataka', 'Raichur'),
('Karnataka', 'Ramanagara'),
('Karnataka', 'Shivamogga'),
('Karnataka', 'Tumakuru'),
('Karnataka', 'Udupi'),
('Karnataka', 'Uttara Kannada'),
('Karnataka', 'Vijayanagar'),
('Karnataka', 'Vijayapura'),
('Karnataka', 'Yadgir'),

-- Madhya Pradesh
('Madhya Pradesh', 'Bhind'),
('Madhya Pradesh', 'Chhatarpur'),
('Madhya Pradesh', 'Damoh'),
('Madhya Pradesh', 'Dindori'),
('Madhya Pradesh', 'Harda'),
('Madhya Pradesh', 'Khargone (West Nimar)'),
('Madhya Pradesh', 'Maihar'),
('Madhya Pradesh', 'Narmadapuram'),
('Madhya Pradesh', 'Raisen'),
('Madhya Pradesh', 'Sagar'),
('Madhya Pradesh', 'Tikamgarh'),
('Madhya Pradesh', 'Ujjain'),
('Madhya Pradesh', 'Agar-Malwa'),
('Madhya Pradesh', 'Alirajpur'),
('Madhya Pradesh', 'Anuppur'),
('Madhya Pradesh', 'Ashoknagar'),
('Madhya Pradesh', 'Balaghat'),
('Madhya Pradesh', 'Barwani'),
('Madhya Pradesh', 'Betul'),
('Madhya Pradesh', 'Bhopal'),
('Madhya Pradesh', 'Burhanpur'),
('Madhya Pradesh', 'Chhindwara'),
('Madhya Pradesh', 'Datia'),
('Madhya Pradesh', 'Dewas'),
('Madhya Pradesh', 'Dhar'),
('Madhya Pradesh', 'Guna'),
('Madhya Pradesh', 'Gwalior'),
('Madhya Pradesh', 'Indore'),
('Madhya Pradesh', 'Jabalpur'),
('Madhya Pradesh', 'Jhabua'),
('Madhya Pradesh', 'Katni'),
('Madhya Pradesh', 'Khandwa (East Nimar)'),
('Madhya Pradesh', 'Mandla'),
('Madhya Pradesh', 'Mandsaur'),
('Madhya Pradesh', 'Morena'),
('Madhya Pradesh', 'Narsimhapur'),
('Madhya Pradesh', 'Neemuch'),
('Madhya Pradesh', 'Niwari'),
('Madhya Pradesh', 'Panna'),
('Madhya Pradesh', 'Rewa'),
('Madhya Pradesh', 'Satna'),
('Madhya Pradesh', 'Sehore'),
('Madhya Pradesh', 'Seoni'),
('Madhya Pradesh', 'Shahdol'),
('Madhya Pradesh', 'Shajapur'),
('Madhya Pradesh', 'Sheopur'),
('Madhya Pradesh', 'Shivpuri'),
('Madhya Pradesh', 'Sidhi'),
('Madhya Pradesh', 'Singrauli'),
('Madhya Pradesh', 'Umaria'),
('Madhya Pradesh', 'Vidisha'),
('Madhya Pradesh', 'MAUGANJ'),
('Madhya Pradesh', 'Pandhurna'),
('Madhya Pradesh', 'Ratlam'),
('Madhya Pradesh', 'Rajgarh'),

-- Uttarakhand
('Uttarakhand', 'Chamoli'),
('Uttarakhand', 'Haridwar'),
('Uttarakhand', 'Nainital'),
('Uttarakhand', 'Pithoragarh'),
('Uttarakhand', 'Almora'),
('Uttarakhand', 'Bageshwar'),
('Uttarakhand', 'Champawat'),
('Uttarakhand', 'Dehradun'),
('Uttarakhand', 'Pauri Garhwal'),
('Uttarakhand', 'Rudra Prayag'),
('Uttarakhand', 'Tehri Garhwal'),
('Uttarakhand', 'Udham Singh Nagar'),
('Uttarakhand', 'Uttarkashi'),

-- Manipur
('Manipur', 'Chandel'),
('Manipur', 'Noney'),
('Manipur', 'Tengnoupal'),
('Manipur', 'Thoubal'),
('Manipur', 'Bishnupur'),
('Manipur', 'Churachandpur'),
('Manipur', 'Imphal East'),
('Manipur', 'Imphal West'),
('Manipur', 'Jiribam'),
('Manipur', 'Kakching'),
('Manipur', 'Kamjong'),
('Manipur', 'Kangpokpi'),
('Manipur', 'Pherzawl'),
('Manipur', 'Senapati'),
('Manipur', 'Tamenglong'),
('Manipur', 'Ukhrul'),

-- Odisha
('Odisha', 'Dhenkanal'),
('Odisha', 'Jagatsinghapur'),
('Odisha', 'Jharsuguda'),
('Odisha', 'Kendrapara'),
('Odisha', 'Malkangiri'),
('Odisha', 'Puri'),
('Odisha', 'Baleshwar'),
('Odisha', 'Balangir'),
('Odisha', 'Bargarh'),
('Odisha', 'Bhadrak'),
('Odisha', 'Boudh'),
('Odisha', 'Cuttack'),
('Odisha', 'Deogarh'),
('Odisha', 'Gajapati'),
('Odisha', 'Ganjam'),
('Odisha', 'Jajapur'),
('Odisha', 'Kalahandi'),
('Odisha', 'Kandhamal'),
('Odisha', 'Koraput'),
('Odisha', 'Mayurbhanj'),
('Odisha', 'Nabarangpur'),
('Odisha', 'Nayagarh'),
('Odisha', 'Nuapada'),
('Odisha', 'Rayagada'),
('Odisha', 'Sambalpur'),
('Odisha', 'Sonepur'),
('Odisha', 'Sundargarh'),
('Odisha', 'Khordha'),

-- Tripura
('Tripura', 'Dhalai'),
('Tripura', 'Khowai'),
('Tripura', 'North Tripura'),
('Tripura', 'South Tripura'),
('Tripura', 'Unakoti'),
('Tripura', 'West Tripura'),
('Tripura', 'Gomati'),
('Tripura', 'Sepahijala'),

-- West Bengal
('West Bengal', 'Dakshin Dinajpur'),
('West Bengal', 'Darjeeling'),
('West Bengal', 'Jalpaiguri'),
('West Bengal', 'Kalimpong'),
('West Bengal', 'Malda'),
('West Bengal', 'South 24 Parganas'),
('West Bengal', 'Uttar Dinajpur'),
('West Bengal', 'Alipurduar'),
('West Bengal', 'Bankura'),
('West Bengal', 'Birbhum'),
('West Bengal', 'Cooch Behar'),
('West Bengal', 'Hooghly'),
('West Bengal', 'Howrah'),
('West Bengal', 'Kolkata'),
('West Bengal', 'Murshidabad'),
('West Bengal', 'Nadia'),
('West Bengal', 'Paschim Bardhaman'),
('West Bengal', 'Paschim Medinipur'),
('West Bengal', 'Purba Medinipur'),
('West Bengal', 'Purulia');

INSERT INTO state_districts (state, district) VALUES
-- Kerala
('Kerala', 'Alappuzha'),
('Kerala', 'Kollam'),
('Kerala', 'Malappuram'),
('Kerala', 'Kasaragod'),
('Kerala', 'Kannur'),
('Kerala', 'Kottayam'),
('Kerala', 'Kozhikode'),
('Kerala', 'Palakkad'),
('Kerala', 'Pathanamthitta'),
('Kerala', 'Thrissur'),
('Kerala', 'Ernakulam'),
('Kerala', 'Idukki'),
('Kerala', 'Thiruvananthapuram'),
('Kerala', 'Wayanad'),

-- Uttar Pradesh
('Uttar Pradesh', 'Ambedkar Nagar'),
('Uttar Pradesh', 'Bahraich'),
('Uttar Pradesh', 'Balrampur'),
('Uttar Pradesh', 'Bhadohi'),
('Uttar Pradesh', 'Chandauli'),
('Uttar Pradesh', 'Jhansi'),
('Uttar Pradesh', 'Kanpur Dehat'),
('Uttar Pradesh', 'Kheri'),
('Uttar Pradesh', 'Kushinagar'),
('Uttar Pradesh', 'Lalitpur'),
('Uttar Pradesh', 'Mainpuri'),
('Uttar Pradesh', 'Mau'),
('Uttar Pradesh', 'Sant Kabir Nagar'),
('Uttar Pradesh', 'Siddharthnagar'),
('Uttar Pradesh', 'Sonbhadra'),
('Uttar Pradesh', 'Unnao'),
('Uttar Pradesh', 'Varanasi'),
('Uttar Pradesh', 'Agra'),
('Uttar Pradesh', 'Aligarh'),
('Uttar Pradesh', 'Amethi'),
('Uttar Pradesh', 'Amroha'),
('Uttar Pradesh', 'Auraiya'),
('Uttar Pradesh', 'Ayodhya'),
('Uttar Pradesh', 'Baghpat'),
('Uttar Pradesh', 'Ballia'),
('Uttar Pradesh', 'Banda'),
('Uttar Pradesh', 'Bara Banki'),
('Uttar Pradesh', 'Bareilly'),
('Uttar Pradesh', 'Basti'),
('Uttar Pradesh', 'Bijnor'),
('Uttar Pradesh', 'Budaun'),
('Uttar Pradesh', 'Bulandshahr'),
('Uttar Pradesh', 'Chitrakoot'),
('Uttar Pradesh', 'Deoria'),
('Uttar Pradesh', 'Etah'),
('Uttar Pradesh', 'Farrukhabad'),
('Uttar Pradesh', 'Fatehpur'),
('Uttar Pradesh', 'Gautam Buddha Nagar'),
('Uttar Pradesh', 'Ghaziabad'),
('Uttar Pradesh', 'Ghazipur'),
('Uttar Pradesh', 'Gonda'),
('Uttar Pradesh', 'Hapur'),
('Uttar Pradesh', 'Hardoi'),
('Uttar Pradesh', 'Hathras'),
('Uttar Pradesh', 'Jalaun'),
('Uttar Pradesh', 'Jaunpur'),
('Uttar Pradesh', 'Kannauj'),
('Uttar Pradesh', 'Kanpur Nagar'),
('Uttar Pradesh', 'Kasganj'),
('Uttar Pradesh', 'Mahoba'),
('Uttar Pradesh', 'Mahrajganj'),
('Uttar Pradesh', 'Mirzapur'),
('Uttar Pradesh', 'Moradabad'),
('Uttar Pradesh', 'Muzaffarnagar'),
('Uttar Pradesh', 'Pilibhit'),
('Uttar Pradesh', 'Pratapgarh'),
('Uttar Pradesh', 'Prayagraj'),
('Uttar Pradesh', 'Raebareli'),
('Uttar Pradesh', 'Rampur'),
('Uttar Pradesh', 'Saharanpur'),
('Uttar Pradesh', 'Sambhal'),
('Uttar Pradesh', 'Shahjahanpur'),
('Uttar Pradesh', 'Shamli'),
('Uttar Pradesh', 'Shravasti'),
('Uttar Pradesh', 'Sitapur'),
('Uttar Pradesh', 'Sultanpur'),

-- Punjab
('Punjab', 'Amritsar'),
('Punjab', 'Fazilka'),
('Punjab', 'Ferozepur'),
('Punjab', 'Sangrur'),
('Punjab', 'S.A.S Nagar'),
('Punjab', 'Shahid Bhagat Singh Nagar'),
('Punjab', 'Pathankot'),
('Punjab', 'Barnala'),
('Punjab', 'Bathinda'),
('Punjab', 'Faridkot'),
('Punjab', 'Fatehgarh Sahib'),
('Punjab', 'Gurdaspur'),
('Punjab', 'Hoshiarpur'),
('Punjab', 'Jalandhar'),
('Punjab', 'Kapurthala'),
('Punjab', 'Ludhiana'),
('Punjab', 'Mansa'),
('Punjab', 'Moga'),
('Punjab', 'Muktsar'),
('Punjab', 'Patiala'),
('Punjab', 'Rupnagar'),
('Punjab', 'Sri Muktsar Sahib'),
('Punjab', 'Tarn Taran'),

-- Gujarat
('Gujarat', 'Arvalli'),
('Gujarat', 'Botad'),
('Gujarat', 'Chhotaudepur'),
('Gujarat', 'Dahod'),
('Gujarat', 'Dangs'),
('Gujarat', 'Gandhinagar'),
('Gujarat', 'Kheda'),
('Gujarat', 'Mahisagar'),
('Gujarat', 'Navsari'),
('Gujarat', 'Porbandar'),
('Gujarat', 'Sabar Kantha'),
('Gujarat', 'Surat'),
('Gujarat', 'Surendranagar'),
('Gujarat', 'Tapi'),
('Gujarat', 'Vadodara'),
('Gujarat', 'Valsad'),
('Gujarat', 'Ahmedabad'),
('Gujarat', 'Amreli'),
('Gujarat', 'Anand'),
('Gujarat', 'Banaskantha'),
('Gujarat', 'Bharuch'),
('Gujarat', 'Bhavnagar'),
('Gujarat', 'Devbhumi Dwarka'),
('Gujarat', 'Gir Somnath'),
('Gujarat', 'Jamnagar'),
('Gujarat', 'Junagadh'),
('Gujarat', 'Kachchh'),
('Gujarat', 'Mahesana'),
('Gujarat', 'Morbi'),
('Gujarat', 'Narmada'),
('Gujarat', 'Panch Mahals'),
('Gujarat', 'Patan'),
('Gujarat', 'Rajkot'),
('Gujarat', 'Sabarkantha'),

-- Bihar
('Bihar', 'Arwal'),
('Bihar', 'Aurangabad'),
('Bihar', 'Katihar'),
('Bihar', 'Madhubani'),
('Bihar', 'Munger'),
('Bihar', 'Patna'),
('Bihar', 'Purbi Champaran'),
('Bihar', 'Samastipur'),
('Bihar', 'Begusarai'),
('Bihar', 'Banka'),
('Bihar', 'Bhagalpur'),
('Bihar', 'Bhojpur'),
('Bihar', 'Buxar'),
('Bihar', 'Darbhanga'),
('Bihar', 'Gaya'),
('Bihar', 'Gopalganj'),
('Bihar', 'Jamui'),
('Bihar', 'Jehanabad'),
('Bihar', 'Kaimur (Bhabua)'),
('Bihar', 'Khagaria'),
('Bihar', 'Kishanganj'),
('Bihar', 'Lakhisarai'),
('Bihar', 'Madhepura'),
('Bihar', 'Muzaffarpur'),
('Bihar', 'Nalanda'),
('Bihar', 'Nawada'),
('Bihar', 'Pashchim Champaran'),
('Bihar', 'Purnia'),
('Bihar', 'Rohtas'),
('Bihar', 'Saharsa'),
('Bihar', 'Samastipur'),
('Bihar', 'Saran'),
('Bihar', 'Sheikhpura'),
('Bihar', 'Sheohar'),
('Bihar', 'Sitamarhi'),
('Bihar', 'Siwan'),
('Bihar', 'Supaul'),
('Bihar', 'Vaishali'),

-- Chhattisgarh
('Chhattisgarh', 'Balod'),
('Chhattisgarh', 'Balrampur-Ramanujganj'),
('Chhattisgarh', 'Bemetara'),
('Chhattisgarh', 'Bijapur'),
('Chhattisgarh', 'Gariyaband'),
('Chhattisgarh', 'Janjgir-Champa'),
('Chhattisgarh', 'Jashpur'),
('Chhattisgarh', 'Kabeerdham'),
('Chhattisgarh', 'Korba'),
('Chhattisgarh', 'Korea'),
('Chhattisgarh', 'Mahasamund'),
('Chhattisgarh', 'Manendragarh-Chirmiri-Bharatpur(M C B)'),
('Chhattisgarh', 'Mohla-Manpur-Ambagarh Chouki'),
('Chhattisgarh', 'Raigarh'),
('Chhattisgarh', 'Raipur'),
('Chhattisgarh', 'Rajnandgaon'),
('Chhattisgarh', 'Sakti'),
('Chhattisgarh', 'Sarangarh-Bilaigarh'),
('Chhattisgarh', 'Surajpur'),
('Chhattisgarh', 'Surguja'),
('Chhattisgarh', 'Dakshin Bastar Dantewada'),
('Chhattisgarh', 'Dhamtari'),
('Chhattisgarh', 'Durg'),
('Chhattisgarh', 'Gaurela-Pendra-Marwahi'),
('Chhattisgarh', 'Bastar'),
('Chhattisgarh', 'Bilaspur'),

-- Jammu And Kashmir
('Jammu And Kashmir', 'Bandipora'),
('Jammu And Kashmir', 'Anantnag'),
('Jammu And Kashmir', 'Baramulla'),
('Jammu And Kashmir', 'Budgam'),
('Jammu And Kashmir', 'Doda'),
('Jammu And Kashmir', 'Ganderbal'),
('Jammu And Kashmir', 'Jammu'),
('Jammu And Kashmir', 'Kathua'),
('Jammu And Kashmir', 'Kishtwar'),
('Jammu And Kashmir', 'Kulgam'),
('Jammu And Kashmir', 'Kupwara'),
('Jammu And Kashmir', 'Poonch'),
('Jammu And Kashmir', 'Pulwama'),
('Jammu And Kashmir', 'Rajouri'),
('Jammu And Kashmir', 'Ramban'),
('Jammu And Kashmir', 'Reasi'),
('Jammu And Kashmir', 'Samba'),
('Jammu And Kashmir', 'Shopian'),
('Jammu And Kashmir', 'Srinagar'),
('Jammu And Kashmir', 'Udhampur'),

-- Maharashtra
('Maharashtra', 'Beed'),
('Maharashtra', 'Bhandara'),
('Maharashtra', 'Chandrapur'),
('Maharashtra', 'Nagpur'),
('Maharashtra', 'Nashik'),
('Maharashtra', 'Palghar'),
('Maharashtra', 'Wardha'),
('Maharashtra', 'Yavatmal'),
('Maharashtra', 'Ahmednagar'),
('Maharashtra', 'Akola'),
('Maharashtra', 'Amravati'),
('Maharashtra', 'Aurangabad'),
('Maharashtra', 'Buldhana'),
('Maharashtra', 'Dhule'),
('Maharashtra', 'Gadchiroli'),
('Maharashtra', 'Gondia'),
('Maharashtra', 'Hingoli'),
('Maharashtra', 'Jalgaon'),
('Maharashtra', 'Jalna'),
('Maharashtra', 'Kolhapur'),
('Maharashtra', 'Latur'),
('Maharashtra', 'Mumbai'),
('Maharashtra', 'Mumbai Suburban'),
('Maharashtra', 'Nanded'),
('Maharashtra', 'Nandurbar'),
('Maharashtra', 'Osmanabad'),
('Maharashtra', 'Parbhani'),
('Maharashtra', 'Pune'),
('Maharashtra', 'Raigad'),
('Maharashtra', 'Ratnagiri'),
('Maharashtra', 'Sangli'),
('Maharashtra', 'Satara'),
('Maharashtra', 'Sindhudurg'),
('Maharashtra', 'Solapur'),
('Maharashtra', 'Thane'),
('Maharashtra', 'Washim');




-- Player Information table
INSERT INTO player_informations (
    playerId,
    jerseyNumber,
    tShirtSize,
    lowerSize,
    hasCricheroesProfile,
    isPaidPlayer,
    pricePerMatch,
    willJoinAnyOwner
)
SELECT
    playerId,
    CASE WHEN RAND() < 0.8 THEN FLOOR(1 + RAND() * 99) END AS jerseyNumber,  -- 80% have numbers
    CASE 
        WHEN RAND() < 0.8 THEN ELT(FLOOR(1 + RAND() * 6), 'XS','S','M','L','XL','XXL')
    END AS tShirtSize,  -- 80% have size
    CASE 
        WHEN RAND() < 0.8 THEN ELT(FLOOR(1 + RAND() * 6), 'XS','S','M','L','XL','XXL')
    END AS lowerSize,  -- 80% have size
    RAND() > 0.4 AS hasCricheroesProfile,  -- 60% true
    RAND() > 0.6 AS isPaidPlayer,  -- 40% true
    CASE 
        WHEN RAND() > 0.6 THEN ROUND(RAND() * 1000, 2)  -- Only for paid players
    END AS pricePerMatch,
    RAND() > 0.3 AS willJoinAnyOwner  -- 70% true
FROM players;